第四回課題作成
akiosako/raisetech_aws pull request #6
Opened 2023-08-25 13:11 UTC by akiosako

第四回課題を作成しました。
ご確認お願いいたします。

2023-08-25 13:47 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +<img width="705" alt="VPC構成図" src="https://github.com/akiosako/raisetech_aws/assets/107123973/17c84c60-709a-45a2-9fd8-3daac06dd755">
markdown記法で表示できるようにご対応ください！
画像のアップ方法も変えないといけないかもです！
```suggestion
![VPC構成図](./???)
```

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +## 第四回課題<br>
改行コードを多用するのはバッドプラクティスなので、適したスタイリングを考えて書いてもらったほうが良いです！
```suggestion
## 第四回課題
```

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +アウトバウンド：全て許可<br>
こんな感じにすると改行コードは要らないと思います！
```suggestion
### EC2作成
* [セキュリティグループの設定]
* インバウンド：マイIPからSSHのみ許可
* アウトバウンド：全て許可
```

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +①EC2起動を起動し、以下コマンドを実行<br>
これは好みかもしれませんが、昔からPCで文字を扱っている人だと「文字化けしやすい文字種」は回避しますね。丸数字がそのひとつです！機種依存文字とかそんなやつです。
```suggestion
1)EC2起動を起動し、以下コマンドを実行
```

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +<img width="481" alt="MySQLの起動を確認" src="https://github.com/akiosako/raisetech_aws/assets/107123973/9c13d680-2dd2-4b24-ba32-aa67e2e0bae5"><br>
ここも他で指摘したように画像埋め込みお願いします！！

2023-08-25 13:47 UTC, MasatoshiMizumoto commented on lecture04.md
> +<img width="487" alt="RDS接続確認" src="https://github.com/akiosako/raisetech_aws/assets/107123973/3cdd41d9-6b62-4c2b-99e9-d55cd0e9f6e7">
ここも他で指摘したように画像埋め込みお願いします！！

2023-08-26 11:49 UTC, akiosako commented on lecture04.md
> +<img width="705" alt="VPC構成図" src="https://github.com/akiosako/raisetech_aws/assets/107123973/17c84c60-709a-45a2-9fd8-3daac06dd755">
- gihutb上でissueを作成
- issueに画像を貼り、URLをコピー
- 画像がHTMLで変換されないようにIDEの設定を変更
上記手順で修正しました。
画像は表示されましたが、問題ないでしょうか。

2023-08-26 12:00 UTC, akiosako commented on lecture04.md
> +## 第四回課題<br>
webで検索しましたら「markdownにおける改行はスペース２つで入れるのが正式」とあったので、そのように修正致しました。

2023-08-26 12:08 UTC, akiosako commented on lecture04.md
> +アウトバウンド：全て許可<br>
上記方法で作成したら、* が・で表示されてしまいました。
もう少し学習してから使いたいと思います。

2023-08-26 12:09 UTC, akiosako commented on lecture04.md
> +①EC2起動を起動し、以下コマンドを実行<br>
数字で対応しました。
記号の選択に気を付けます。

2023-08-26 13:55 UTC, MasatoshiMizumoto commented
画像ってどうやってGitHubに送りましたかね？
削除するのが手間だと思うので、コードと同じように送ってほしいです！

2023-08-27 05:30 UTC, MasatoshiMizumoto requested changes
画像の表示はOKですね！
あと追加ですいませんが、EC2とRDSが作成したVPC上に構築されているかのエビデンスも欲しいです！

2023-08-27 05:59 UTC, MasatoshiMizumoto approved these changes
LGTM!
お疲れさまでした！

2023-08-27 06:11 UTC, merged